sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: n38CVfRF+HQH3nkYu0aaShd9wzihjN67yeYanObf32uFGdUxv6Sl5+/mxspEcqEQ5ULE5O2fhekp+eBuYIgykIu39NobCkzfM+hszkVV5v9JsX89QFY0mY2K54/LAP1rKGIGYVjWC0CK9z7SFbtUzV+ZUUA9VIrfjO0vnCuRk1/4hB+3qBxSvKobkAzkJgO3RPgiDxkV67qBIx0EujuQ1edi/8FnVlkrrnlBgl1UzCJpKUP48URR4E5KoVBQCqUgjKxRWHPthdkpCB13N330TmYJrkFUct5MxxMTXopw1E+B+C8WtZ09SsA7gf2hv3iWk6uXQd9TSMJLnyXP10cnBBnU3DArIfbGbatI8XZ/EsNIP9q4wN45TnOGUupAF6AQojCi2rM5+3bUx/490KAwpJpM08k/PoLZHCAMJmu6OKLg3V8q2J7WDcajeA544wutqkML1yatdHwFsVrvQcLqJxTt3tLR7a+vmWX0PDo5R+dVP4AsoOj/KD0b/T8ZtqTwkRPNnbuPdfqhM6gQLylc1UPujkd9ugTq1wskLzP+dh2KIp72YpCjUvn5UldkTpAqGe8XHRZyBhDl54gKAyyLdhGb3SOrk/8lbT6KNedX5jU30/JUpjg6jg3vHSgYTHYyRTRDgaHjIGfu9lGTXCYJ/HkZfcW9FYkzwfMNRVp8t6U=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Private-Papers-of-Henry-Ryecroft_1463
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy